### ISSUE TITLE
Move StockpileFixer to its own repository

### ISSUE THREAD

**Issue by scowalt** [redscientistlabs/Bizhawk-Vanguard#19]

**Comment by NarryG** [comment]
StockpileFixer can just go completely. It no longer serves a purpose. It was a simple helper tool to migrate some stockpiles during dev builds where we changed how some of the file paths were managed years ago now. It somehow never got removed from this repo when we moved past the 32X branch

**Comment by NarryG** [comment]
Done with https://github.com/redscientistlabs/Bizhawk-Vanguard/commit/738878827655459f6e4ad5df1f4a0c82e0309ef3
